### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by corysimmons** [lukehorvat/react-osx-dock#4]
Cool idea and the demo works but I get no scaling when I hover with the quickstart code. I can see it hasn't been updated in a couple years but in future projects, please provide quickstart code that works, and/or don't minify the working demo in `gh-pages` please.

**Comment by lukehorvat** [comment]
See the `demo` branch for non-minified code.

**Comment by corysimmons** [comment]
Ah, my bad. Thank you
